name: Docker Image CI
#CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Build the Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build  --platform linux --tag ccamsoto/ci:latest -f ci-cd/dockerfile .
      - name: Push the Docker image
        run: docker push ccamsoto/ci:latest
        #CD
      - name: App service auth
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'camilocsoto'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ccamsoto/ci:latest'
